### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by M-Mahou** [deep-floyd/IF#16]
![image](https://user-images.githubusercontent.com/95573111/234677950-cb890360-0b45-4525-a869-3bd8708a0c40.png)

Kinda a newbie, to github/huggingface/colab/Everything

When going to this link https://huggingface.co/DeepFloyd/IF-I-IF-v1.0/resolve/main/text_encoder/config.json 
it responds with Repo not found 
![image](https://user-images.githubusercontent.com/95573111/234678426-4cf0d686-e922-4652-be02-ab7e02d5342c.png)

**Comment by Mefistofelesxxx** [comment]
The same here dude

**Comment by jepjoo** [comment]
Weights are not available yet. README.md says soon.

"The link to download the weights as well as the model cards will be available soon on each model of the model zoo"

**Comment by designium** [comment]
I have the same issue.

**Comment by InCrIpTiOn** [comment]
@jepjoo Researcher said couple of days, source: https://twitter.com/EMostaque/status/1651333336948719616?s=20

**Comment by shonenkov** [comment]
weights are available, problem is not actual
