### ISSUE TITLE
Unreadable notebook

### ISSUE THREAD

**Issue by IceTea42** [deep-floyd/IF#29]
When I tried to open and try the notebook (via jupyter notebook) I've got the following error message: 
 ```
Error loading notebook
Unreadable Notebook: /home/ogem/codes/public/2023/IF/notebooks/pipes-DeepFloyd-IF.ipynb NotJSONError("Notebook does not appear to be JSON: 'version https://git-lfs.github.com/spec...")
```
Is there a json syntax error? Or maybe there is another way to open and use the notebook?

**Comment by pixelkaiser** [comment]
The notebook is hosted in lfs and the quota is depleted. Do 

`git lfs pull
`

And you will get:


```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/deep-floyd/IF.git/info/lfs'
```

**Comment by IceTea42** [comment]
@pixelkaiser you are right and thanks for the response. I'll keep the issue open - maybe they find a way to make the notebook available

**Comment by shonenkov** [comment]
thank you - going to fix this

**Comment by shonenkov** [comment]
I moved notebook from github LFS to HF:

notebook is available here: https://huggingface.co/DeepFloyd/IF-I-XL-v1.0/tree/main/notebooks

**Comment by IceTea42** [comment]
Thanks for the response. But the link doesn't work, maybe forgot to make it public?

**Comment by IceTea42** [comment]
Thanks
