### ISSUE TITLE
UNetModel parameters

### ISSUE THREAD

**Issue by ulysso** [deep-floyd/IF#31]
Would it be possible to please post the `UNetModel(**model_params)` so devs can work on integrating/optimizing already just with randomly initialized weights until the actual ones are released? 

Would be great to allow testing optimization ideas and things like that but hard without knowing the exact size, and I couldn't find that in the code currently unless I missed it.

**Comment by matbeedotcom** [comment]
Would be good just to prep some user-facing implementations too
