### ISSUE TITLE
Is this really Open Source?

### ISSUE THREAD

**Issue by phalexo** [deep-floyd/IF#58]
Then  why is this file behind a login?

https://huggingface.co/DeepFloyd/IF-I-XL-v1.0/resolve/main/config.yml

I just want to run it on my server, use my GPUs, storage, etc...

**Comment by nbardy** [comment]
Give them time to fix mistakes. The release just happened there is a lot to get right.

**Comment by kanttouchthis** [comment]
> Give them time to fix mistakes. The release just happened there is a lot to get right.

it's not a mistake. while the code is open source, the actual models are not (yet), as the README.md says.
>Disclaimer: The initial release of the IF model is under a restricted research-purposes-only license temporarily to gather feedback, and after that we intend to release a fully open-source model in line with other Stability AI models.
